In [1]:
import pandas as pd
!pip install requests

Requirement already satisfied: requests in c:\users\kothari\appdata\local\programs\python\python37\lib\site-packages (2.27.1)
Requirement already satisfied: charset-normalizer~=2.0.0; python_version >= "3" in c:\users\kothari\appdata\local\programs\python\python37\lib\site-packages (from requests) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\kothari\appdata\local\programs\python\python37\lib\site-packages (from requests) (2021.10.8)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\kothari\appdata\local\programs\python\python37\lib\site-packages (from requests) (1.26.9)
Requirement already satisfied: idna<4,>=2.5; python_version >= "3" in c:\users\kothari\appdata\local\programs\python\python37\lib\site-packages (from requests) (3.3)

WARNING: You are using pip version 20.1.1; however, version 22.0.4 is available.
You should consider upgrading via the 'c:\users\kothari\appdata\local\programs\python\python37\python.exe -m pip install --upgrade pip' command.

In [2]:
import requests

In [3]:
response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=4aedd2ae8f4cc2e9a045326bffc26095&language=en-US&page=1')

In [4]:
pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]

,id,title,overview,release_date,popularity,vote_average,vote_count
0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,79.480,8.7,21011
1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,30.856,8.7,3525
2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,104.510,8.7,15697
3,533514,Violet Evergarden: The Movie,As the world moves on from the war and technol...,2020-09-18,31.679,8.7,203
4,730154,Your Eyes Tell,"A tragic accident lead to Kaori's blindness, b...",2020-10-23,13.240,8.7,272
5,424,Schindler's List,The true story of how businessman Oskar Schind...,1993-11-30,64.845,8.6,12537
6,372754,Dou kyu sei â€“ Classmates,"Rihito Sajo, an honor student with a perfect s...",2016-02-20,16.866,8.6,212
7,724089,Gabriel's Inferno Part II,Professor Gabriel Emerson finally learns the t...,2020-07-31,12.377,8.6,1389
8,240,The Godfather: Part II,In the continuing saga of the Corleone crime f...,1974-12-20,74.720,8.6,9456
9,696374,Gabriel's Inferno,An intriguing and sinful exploration of seduct...,2020-05-29,12.637,8.6,2216
10,761053,Gabriel's Inferno Part III,The final part of the film adaption of the ero...,2020-11-19,25.426,8.6,948
11,372058,Your Name.,High schoolers Mitsuha and Taki are complete s...,2016-08-26,165.992,8.5,8475
12,129,Spirited Away,"A young girl, Chihiro, becomes trapped in a st...",2001-07-20,96.774,8.5,12586
13,496243,Parasite,"All unemployed, Ki-taek's family takes peculia...",2019-05-30,107.081,8.5,13327
14,255709,Hope,After 8-year-old So-won narrowly survives a br...,2013-10-02,21.455,8.5,336
15,389,12 Angry Men,The defense and the prosecution have rested an...,1957-04-10,37.722,8.5,6269
16,497,The Green Mile,A supernatural tale set on death row in a Sout...,1999-12-10,85.911,8.5,13668
17,632632,Given,The film centers on the love relationship amon...,2020-08-22,105.610,8.5,306
18,155,The Dark Knight,Batman raises the stakes in his war on crime. ...,2008-07-14,125.842,8.5,27123
19,283566,Evangelion: 3.0+1.0 Thrice Upon a Time,"In the aftermath of the Fourth Impact, strande...",2021-03-08,150.507,8.5,474

In [5]:
#creating an empty df
df = pd.DataFrame()

In [6]:
for i in range(1,429):
    response = requests.get('https://api.themoviedb.org/3/movie/top_rated?api_key=4aedd2ae8f4cc2e9a045326bffc26095&language=en-US&page={}'.format(i))
    temp_df = pd.DataFrame(response.json()['results'])[['id','title','overview','release_date','popularity','vote_average','vote_count']]
    df.append(temp_df,ignore_index=True)

In [8]:
#https://rapidapi.com/collection/list-of-free-apis

In [12]:
df2 = pd.read_csv('movies.csv')
df2.head()

,Unnamed: 0,id,title,overview,release_date,popularity,vote_average,vote_count
0,0,278,The Shawshank Redemption,Framed in the 1940s for the double murder of h...,1994-09-23,79.480,8.7,21011
1,1,19404,Dilwale Dulhania Le Jayenge,"Raj is a rich, carefree, happy-go-lucky second...",1995-10-20,30.856,8.7,3525
2,2,238,The Godfather,"Spanning the years 1945 to 1955, a chronicle o...",1972-03-14,104.510,8.7,15697
3,3,533514,Violet Evergarden: The Movie,As the world moves on from the war and technol...,2020-09-18,31.679,8.7,203
4,4,730154,Your Eyes Tell,"A tragic accident lead to Kaori's blindness, b...",2020-10-23,13.240,8.7,272